name: "Develop CI/CD Pipeline"
on:
  push:
    branches:
      - development


env:
  REPO_NAME:  ${{ github.event.repository.name }} 
  REGISTRY_URL: gravitate-registry.cr.de-fra.ionos.com
  
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    container: node:lts
    steps:
    - id: environment
      run: |
        echo "::set-output name=image::${REGISTRY_URL}/${REPO_NAME}"
    outputs:
      image: ${{ steps.environment.outputs.image }}
  
  docker:
    needs: [setup-environment]
    env:
      TAG: ${{ '1.1.0' }}
      IMAGE: ${{ needs.setup-environment.outputs.image }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GH registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push
        run: |
          sudo docker build -t ${{ env.IMAGE }}:${{ env.TAG }} .
          docker push ${{ env.IMAGE }}:${{ env.TAG }}
